#%RAML 1.0 NamedExample
[{
  "BillingCity" : "Chennai",
  "BillingCountry" : "India",
  "BillingGeocodeAccuracy" : "",
  "BillingLatitude" : "",
  "BillingLongitude" : "",
  "BillingPostalCode" : "",
  "BillingState" : "",
  "BillingStreet" : "",
  "Name" : "Assessment test1",
  "Phone" : "1111111111",
  "ShippingCity" : "Houston",
  "ShippingCountry" : "United States",
  "ShippingLatitude" : "",
  "ShippingLongitude" : "",
  "ShippingPostalCode" : "77002",
  "ShippingState" : "Texas",
  "ShippingStreet" : "Cherry Crk"
}]