#%RAML 1.0 NamedExample
{
  "BillingCity" : "Pittsboro",
  "BillingCountry" : "United States	",
  "BillingGeocodeAccuracy" : "",
  "BillingLatitude" : "",
  "BillingLongitude" : "",
  "BillingPostalCode" : "27312",
  "BillingState" : "NC",
  "BillingStreet" : "220 Lorax Lane	",
  "Email__c" : "",
  "Phone" : "",
  "ShippingAddress" : "",
  "ShippingCity" : "",
  "ShippingCountry" : "",
  "ShippingLatitude" : "",
  "ShippingLongitude" : "",
  "ShippingPostalCode" : "",
  "ShippingState" : "",
  "ShippingStreet" : ""
}