#%RAML 1.0 NamedExample
#%RAML 1.0 NamedExample
{
  "BillingCity" : "Pittsboro",
  "BillingCountry" : "United States	",
  "BillingGeocodeAccuracy" : "",
  "BillingLatitude" : "",
  "BillingLongitude" : "",
  "BillingPostalCode" : "27312",
  "BillingState" : "NC",
  "BillingStreet" : "220 Lorax Lane	",
  "CreatedById" : "",
  "Email__c" : "abc@gmail.com",
  "Name" : "Customer",
  "Phone" : "1111111111",
  "ShippingAddress" : "123 Amola Park",
  "ShippingCity" : "Houston",
  "ShippingCountry" : "United States	",
  "ShippingLatitude" : "",
  "ShippingLongitude" : "",
  "ShippingPostalCode" : "77002",
  "ShippingState" : "Texas",
  "ShippingStreet" : "Cherry Crk"
}